attributes:
- extraction_patterns:
  - within (\d+) days
  - no later than (\d+) days
  - (\d+)[-\s]day.*filing
  name: Medicaid Timely Filing
  section_patterns:
  - Submission and Adjudication of Medicaid Claims
  - Medicaid.*Claims.*Submission
  - Timely Filing.*Medicaid
  typical_values:
    TN: 120 days
    WA: 180 days
- extraction_patterns:
  - within (\d+) days
  - no later than (\d+) days
  - (\d+)[-\s]day.*filing
  name: Medicare Timely Filing
  section_patterns:
  - Submission and Adjudication of Medicare.*Claims
  - Medicare.*Claims.*Submission
  - Timely Filing.*Medicare
  typical_values:
    TN: 90 days
    WA: 90 days
- extraction_patterns:
  - Provider shall be eligible.*Networks
  - participate.*in.*Networks designated
  - Network.*designation.*on
  name: No Steerage/SOC
  section_patterns:
  - Networks and Provider Panels
  - Network.*Participation
  - Provider.*Panels
  typical_values:
    TN: Standard network participation
    WA: Standard network participation
- extraction_patterns:
  - (\d+)%?\s*of.*Fee Schedule
  - Fee Schedule.*(\d+)%?
  - Medicaid.*Rate.*(\d+)%?
  name: Medicaid Fee Schedule
  section_patterns:
  - Plan Compensation Schedule
  - Specific Reimbursement Terms
  - Medicaid.*Rate.*Methodology
  typical_values:
    TN: 100% of Fee Schedule
    WA: 95% of Fee Schedule
- extraction_patterns:
  - (\d+)%?\s*of.*Medicare.*Fee
  - Medicare.*Rate.*(\d+)%?
  - lesser of.*Charges.*or.*Medicare
  name: Medicare Fee Schedule
  section_patterns:
  - Plan Compensation Schedule
  - Specific Reimbursement Terms
  - Medicare.*Rate.*Methodology
  typical_values:
    TN: 100% of Medicare Rate
    WA: 100% of Medicare Rate
classification:
  exact:
    weight: 0.2
  fuzzy:
    partial_ratio_threshold: 75
    token_set_ratio_threshold: 85
    token_sort_ratio_threshold: 80
    weight: 0.3
  model_type: hybrid
  semantic:
    enabled: true
    model_name: sentence-transformers/all-MiniLM-L6-v2
    threshold: 0.75
    weight: 0.5
  thresholds:
    critical_attributes:
    - Medicaid Timely Filing
    - Medicare Timely Filing
    critical_threshold: 0.6
    non_standard: 0.8
    standard: 0.8
export:
  formats:
  - csv
  - json
  - excel
  include_audit_trail: true
  include_confidence_scores: true
logging:
  file: contract_classification.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
ocr:
  dpi: 300
  enabled: true
  language: eng
paths:
  attribute_dict: ./HiLabsAIQuest_ContractsAI/Attribute_Dictionary.xlsx
  cache_dir: ./cache
  contracts_dir: ./HiLabsAIQuest_ContractsAI/Contracts
  output_dir: ./output
  templates_dir: ./HiLabsAIQuest_ContractsAI/Standard_Templates
pdf_extraction:
  detect_vertical: false
  keep_blank_chars: true
  layout_mode: true
  x_tolerance: 3
  y_tolerance: 3
performance:
  batch_size: 10
  cache_embeddings: true
  max_file_size_mb: 50
  parallel_workers: 4
  timeout_seconds: 30
preprocessing:
  normalize_whitespace: true
  remove_headers_footers: true
  remove_page_numbers: true
states:
- TN
- WA
ui:
  enable_side_by_side_comparison: true
  max_upload_size_mb: 200
  show_confidence_scores: true
  theme: light
  title: HiLabs Healthcare Contract Classification System
